### ISSUE TITLE
Android Build breaks with react-native@0.47.0

### ISSUE THREAD

**Issue by robertmerten** [adjust/react_native_sdk#16]
See Breaking Changes:

https://github.com/facebook/react-native/releases

Android

Remove unused createJSModules calls (ce6fb33, 53d5504) - @javache

`node_modules/react-native-adjust/android/src/main/java/com/adjust/sdk/AdjustPackage.java:30: error: method does not override or implement a method from a supertype`

**Comment by uerceg** [comment]
@robertmerten 

Thanks for the info, we have started to work on v4.11.4 update that will make SDK compliant with these React Native changes. Will keep you posted.

Cheers

**Comment by uerceg** [comment]
@robertmerten 

We have updated our SDK. Feel free to give it a try and see if the issue is resolved: https://github.com/adjust/react_native_sdk/releases/tag/v4.11.4

Cheers

**Comment by robertmerten** [comment]
@uerceg Works now, Thx!

**Comment by uerceg** [comment]
🎉  Great! Thank you one more time for reporting this!

Cheers. 🍺
